### PR TITLE
Fix `export` command

### LINKED ISSUE #246: Bug: `export` command creates multiple columns for a session if the session name contains commas
A possible fix is to enforce session names to not contain commas

### PR DESCRIPTION
**Pull request by njxue**
Resolves #246 
* Enforce session names to contain only letters, digits, whitespace or underscores
  * Session names can begin with whitespaces. This was not allowed previously, please lmk if this change needs to be reverted
* The UG will be updated separately in #242

### CODE REVIEW

File: src/test/java/seedu/taassist/model/session/SessionTest.java [hunk 1]
```diff
@@ -75,12 +75,10 @@ public void equals_diffValues_returnsFalse() {
...
-        // special characters and whitespaces are allowed
-        assertTrue(Session.isValidSessionName("+/~@#$%^&* "));
-
-        // sessions names beginning with whitespaces are not allowed
-        assertFalse(Session.isValidSessionName(" Assignment 1"));
-
+        // underscores and whitespace are allowed
+        assertTrue(Session.isValidSessionName("_LAB 1_"));
+        // special characters are not allowed
+        assertFalse(Session.isValidSessionName("+/~@#$%^&* "));
```
Comment (Bubbl3T) [inline src/test/java/seedu/taassist/model/session/SessionTest.java:81]: Based on EP we shouldn't have so many invalid symbols in a single test case, but I guess the intention is just to show that the method will return false, so I guess this is fine.

**Review by Bubbl3T — APPROVED** [review]
LGTM!

File: src/test/java/seedu/taassist/model/session/SessionTest.java (hunk 1 above)
Comment (njxue) [reply src/test/java/seedu/taassist/model/session/SessionTest.java:81]: Yea,, we should look into EP in #241 but this should suffice for now
