### PR TITLE
Fix issues related to help window

### LINKED ISSUE #25: Help window working incorrectly on Linux
- The help window is not loading on Linux (Arch) and shows the following: 
Screenshot_20220927_203017
- When opened for the second time, it loads with correct size. 
- The button and the text is not centered vertically.

### PR DESCRIPTION
**Pull request by RezwanArefin01**
Fixes #25. Changes: 
* Remove javafx version checking from `.fxml` file. Previously inconsistent versions were in use.
* Move usages of `helpMessage` outside constructor of `HelpMessage`. Since this variable expected to be populated after the construction ends.
* Force a recalculation of stage size after setting the help message. 
* Vertically center the help message and "Copy URL" button. Previously it was not centered.  
* Point the URL to our product website.

### CODE REVIEW

File: src/main/java/seedu/address/ui/HelpWindow.java [hunk 1]
```diff
@@ -15,7 +15,7 @@
  */
 public class HelpWindow extends UiPart<Stage> {
 
-    public static final String USERGUIDE_URL = "https://se-education.org/addressbook-level3/UserGuide.html";
+    public static final String USERGUIDE_URL = "https://nus-cs2103-ay2223s1.github.io/tp/UserGuide.html";
```
Comment (njxue) [inline src/main/java/seedu/address/ui/HelpWindow.java]: I think the url for the UG should be https://ay2223s1-cs2103t-t12-1.github.io/tp/UserGuide.html

**Review by njxue — CHANGES_REQUESTED** [review]

**Review by njxue — APPROVED** [review]

**Comment by njxue** [comment]
LGTM!
