### PR TITLE
Fix bug: deleting focused class does not unfocus

### LINKED ISSUE #270: Deleting focused class does not exit focus mode
Similar to #254.

### PR DESCRIPTION
**Pull request by RezwanArefin01**
Fixes #270

### CODE REVIEW

File: src/main/java/seedu/taassist/logic/commands/DeletecCommand.java [hunk 1]
```diff
@@ -52,10 +52,17 @@ public CommandResult execute(Model model) throws CommandException {
                 nonExistentClasses.add(moduleClass);
             }
         }
+
+        boolean isDeletingFocusedClass = model.isInFocusMode()
+                && existingClasses.stream().anyMatch(c -> c.isSame(model.getFocusedClass()));
+        if (isDeletingFocusedClass) {
```
Comment (Berted) [inline src/main/java/seedu/taassist/logic/commands/DeletecCommand.java:58]: Should this code block be handled in `model` instead? However, I understand it can be quite challenging with the design of `CommandResult`.

**Review by Berted — APPROVED** [review]
LGTM! Optionally, one part of the code can be improved upon to prevent breaking the Seperation of Concern-s principle.
