### PR TITLE
Fix deletec command

### LINKED ISSUE #100: `deletec` command runs into RuntimeException with incorrect format
Executing `deletec` without `c/` (eg. `deletec foobarbaz`) causes an uncaught RuntimeException.

Consider:
1. Removing the `c/` requirement, or
2. Keep the `c/` requirement, but allow deleting multiple classes at once

### PR DESCRIPTION
**Pull request by njxue**
Fixes #100 but not #87

1. Now supports deletion of multiple classes at one go
2. Returns error message when prefix is not provided
3. Returns error message when prefix argument is empty

### CODE REVIEW

File: src/main/java/seedu/taassist/logic/parser/DeletecCommandParser.java [hunk 1]
```diff
@@ -21,10 +23,22 @@ public class DeletecCommandParser implements Parser<DeletecCommand> {
...
         } catch (ParseException pe) {
-            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, DeleteCommand.MESSAGE_USAGE), pe);
+            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, DeletecCommand.MESSAGE_USAGE), pe);
         }
     }
+
+    /**
+     * Returns true if the prefix for the command is present and non-empty.
+     */
+    private static boolean isPrefixPresentAndNotEmpty(ArgumentMultimap argumentMultimap, Prefix prefix) {
```
Comment (RezwanArefin01) [inline src/main/java/seedu/taassist/logic/parser/DeletecCommandParser.java]: This function does not sound like it belongs here. 

Currently there are similar methods in other `*Parser` classes too. Wouldn't it be better to move them into a util class?

File: src/main/java/seedu/taassist/model/ModelManager.java [hunk 2]
```diff
@@ -133,6 +134,13 @@ public void deleteModuleClass(ModuleClass target) {
         taAssist.removeModuleClass(target);
     }
 
+    @Override
+    public void deleteModuleClasses(Collection<ModuleClass> moduleClasses) {
+        for (ModuleClass moduleClass : moduleClasses) {
```
Comment (RezwanArefin01) [inline src/main/java/seedu/taassist/model/ModelManager.java:146]: `null` check is missing. `moduleClasses` as well as each `moduleClass` need not be `null`.

File: src/main/java/seedu/taassist/model/Model.java [hunk 3]
```diff
@@ -99,6 +100,12 @@ public interface Model {
      */
     void deleteModuleClass(ModuleClass moduleClass);
 
+    /**
+     * Deletes multiple classes.
+     * The classes must exist in TA-Assist.
+     */
+    void deleteModuleClasses(Collection<ModuleClass> moduleClasses);
+
```
Comment (RezwanArefin01) [inline src/main/java/seedu/taassist/model/Model.java:108]: How about `deleteModuleClasses(ModuleClass... moduleClass)` instead of these two methods? Might have pros and cons.

**Review by RezwanArefin01 — COMMENTED** [review]
Commented on some alternative approaches to consider.

File: src/main/java/seedu/taassist/model/Model.java (hunk 3 above)
Comment (njxue) [reply src/main/java/seedu/taassist/model/Model.java:108]: I think I'll leave it as it is for now, because otherwise, we will have to convert `Collection<ModuleClass>` to an array everytime we want to delete multiple classes since varargs only accept Arrays.

File: src/main/java/seedu/taassist/logic/parser/DeletecCommandParser.java (hunk 1 above)
Comment (njxue) [reply src/main/java/seedu/taassist/logic/parser/DeletecCommandParser.java]: Good idea, I shifted it to `ParserUtil`.

File: src/main/java/seedu/taassist/logic/parser/ParserUtil.java [hunk 4]
```diff
@@ -140,4 +140,12 @@ public static Set<ModuleClass> parseModuleClasses(Collection<String> moduleClass
         }
         return moduleClassSet;
     }
+
+    /**
+     * Returns true if the {@code prefix} does not contain empty {@code Optional} values in the given
+     * {@code ArgumentMultimap}.
+     */
+    public static boolean isPrefixPresent(ArgumentMultimap argumentMultimap, Prefix prefix) {
```
Comment (RezwanArefin01) [inline src/main/java/seedu/taassist/logic/parser/ParserUtil.java]: Currently this class is only parsing strings. How about moving this function to `ArgumentMultimap`? 
Also similar can be done for other `*Parser` classes that have a method on `ArgumentMultimap`.

File: src/main/java/seedu/taassist/model/Model.java [hunk 5]
```diff
@@ -108,6 +115,9 @@ public interface Model {
     /** Returns an unmodifiable view of the module class list */
     ObservableList<ModuleClass> getModuleClassList();
 
+    /** Checks if all {@code moduleClass} in {@code moduleClasses} exists */
+    boolean areAllExistingModuleClasses(Collection<ModuleClass> moduleClasses);
```
Comment (RezwanArefin01) [inline src/main/java/seedu/taassist/model/Model.java]: How about naming it `hasModuleClasses`? Since there is `deleteModuleClass` and `deleteModuleClasses`, I think that would be better.

**Review by RezwanArefin01 — CHANGES_REQUESTED** [review]
Suggested some minor changes.

File: src/main/java/seedu/taassist/logic/parser/ParserUtil.java (hunk 4 above)
Comment (njxue) [reply src/main/java/seedu/taassist/logic/parser/ParserUtil.java]: Nice suggestion. In that case, I made it non-static and allowed checking of multiple prefixes

**Review by RezwanArefin01 — APPROVED** [review]
Looks good to merge!
