### PR TITLE
Fix `add` and `edit` commands not showing filtered list bug

### LINKED ISSUE #222: Bug: Adding new students while in focus mode shows the entire list of students instead of only class students

### PR DESCRIPTION
**Pull request by njxue**
Resolves #222

### CODE REVIEW

File: src/main/java/seedu/taassist/logic/commands/DeletesCommand.java [hunk 1]
```diff
@@ -19,14 +19,14 @@ public class DeletesCommand extends Command {
 
     public static final String COMMAND_WORD = "deletes";
 
-    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Delete sessions for a class. "
+    public static final String MESSAGE_USAGE = "> Deletes sessions for a class.\n"
```
Comment (Bubbl3T) [inline src/main/java/seedu/taassist/logic/commands/DeletesCommand.java:22]: I believe the original version is kept to maintain consistency for all the commands. Perhaps we can decide on the actual formatting in v1.4.

File: src/main/java/seedu/taassist/logic/commands/DeletesCommand.java [hunk 2]
```diff
@@ -19,14 +19,14 @@ public class DeletesCommand extends Command {
...
             + "Paramaters: "
             + PREFIX_SESSION + "SESSION_NAME\n"
             + "Example: " + COMMAND_WORD + " "
             + PREFIX_SESSION + "Lab1";
 
     public static final String MESSAGE_SUCCESS = "Sessions deleted: %s";
-    public static final String MESSAGE_SESSION_DOES_NOT_EXIST = "Session %s does not exist!";
+    public static final String MESSAGE_SESSION_DOES_NOT_EXIST = "Session [ %s ] does not exist!";
```
Comment (Bubbl3T) [inline src/main/java/seedu/taassist/logic/commands/DeletesCommand.java:29]: This formatting might need to change if we want to allow users to delete multiple sessions at once. Specific formatting can be discussed in v1.4.

File: src/main/java/seedu/taassist/model/Model.java [hunk 3]
```diff
@@ -131,11 +131,6 @@ public interface Model {
      */
     void removeModuleClasses(Collection<ModuleClass> moduleClasses);
 
-    /**
-     * Removes the specified {@code session} from the specified {@code moduleClass}.
-     */
-    void removeSession(ModuleClass moduleClass, Session session);
```
Comment (Bubbl3T) [inline src/main/java/seedu/taassist/model/Model.java:137]: Is there a reason why we are removing this method? 😅

**Review by Bubbl3T — APPROVED** [review]
LGTM!
