### PR TITLE
Fix UI button not exiting focus mode bug

### LINKED ISSUE #237: Bug: UI button not exiting focus mode

### PR DESCRIPTION
**Pull request by optionalemon**

### CODE REVIEW

File: src/main/java/seedu/taassist/ui/MainWindow.java [hunk 1]
```diff
@@ -178,7 +178,7 @@ private void handleFocusMode() {
     }
 
     @FXML
-    private void handleUnfocusMode() {
+    private void handleUnfocusMode() throws CommandException, ParseException {
```
Comment (RezwanArefin01) [inline src/main/java/seedu/taassist/ui/MainWindow.java]: `throws CommandException, ParseException` is unnecessary here. I guess it was added by IDE.

File: src/main/java/seedu/taassist/ui/MainWindow.java [hunk 2]
```diff
@@ -189,6 +189,11 @@ private void handleUnfocusMode() {
         moduleClassListPanelPlaceholder.getChildren().add(moduleClassListPanel.getRoot());
     }
 
+    @FXML
+    private void buttonHandleUnfocus() throws CommandException, ParseException {
+        executeCommand("unfocus");
```
Comment (RezwanArefin01) [inline src/main/java/seedu/taassist/ui/MainWindow.java]:
```suggestion
        try { 
            executeCommand("unfocus");
        } catch (Exception e) {
            assert false; 
        }
```

**Review by RezwanArefin01 — CHANGES_REQUESTED** [review]
Suggested some changes regarding error handling.

**Review by RezwanArefin01 — APPROVED** [review]
Looks good to merge!
