### PR TITLE
Fix bug in deleting classes from TA Assist

### LINKED ISSUE #87: Bug: deleting a class does not unassign students from the class
I'm concerned with the following scenario:
- Classes only consists of `CS1231S` and `CS2030S`
- A student is tagged with class `CS2100`, but it doesn't exist

Whilst it's not behaviour that breaks anything for now, it might be problematic down the line.

_Originally posted by @Berted in https://github.com/AY2223S1-CS2103T-T12-1/tp/pull/80#discussion_r988496119_

### PR DESCRIPTION
**Pull request by Bubbl3T**
The `deletec` command does not unassign students from the class when it is deleted.
This may cause problems where classes that do not exist in TA Assist are being assigned to students.

Let's change the implementation of `deletec` command so that it unassigns students from the classes that will be deleted.

Closes #87.

### CODE REVIEW

File: src/main/java/seedu/taassist/logic/commands/DeletecCommand.java [hunk 1]
```diff
@@ -41,6 +45,18 @@ public CommandResult execute(Model model) throws CommandException {
                     model.getModuleClassList()));
         }
 
+        List<Student> students = model.getFilteredStudentList();
```
Comment (Berted) [inline src/main/java/seedu/taassist/logic/commands/DeletecCommand.java]: Shouldn't we delete from the entire `model` list? Instead of just the filtered model list.

File: src/main/java/seedu/taassist/logic/commands/DeletecCommand.java [hunk 2]
```diff
@@ -41,6 +45,18 @@ public CommandResult execute(Model model) throws CommandException {
...
+        for (Student student : students) {
+            if (!Collections.disjoint(student.getModuleClasses(), moduleClasses)) {
+                Set<ModuleClass> assignedClasses = new HashSet<>();
+                assignedClasses.addAll(student.getModuleClasses());
+                assignedClasses.removeAll(moduleClasses);
```
Comment (Berted) [inline src/main/java/seedu/taassist/logic/commands/DeletecCommand.java:60]: I believe this doesn't achieve the intended behavior? 

In this case, comparing equality should use the `ModuleClass::isSame` method. Doing `removeAll` in this scenario will check by `ModuleClass::equals` and remove it based on that. Perhaps this is also a design issue that can be looked into again.

**Review by Berted — CHANGES_REQUESTED** [review]
Nice work! However, I believe the code can fail in certain scenarios. (i.e. when there are sessions in a ModuleClass)

File: src/main/java/seedu/taassist/logic/commands/DeletecCommand.java (hunk 2 above)
Comment (Berted) [reply src/main/java/seedu/taassist/logic/commands/DeletecCommand.java:60]: After further thought. This design is fine for now, since `Student`-s always store moduleClasses with empty `List<Sessions>` in practice. However, this could end up being confusing in the long run. We'll probably need to introduce some interface to be returned instead of a `Set<ModuleClass>`. Will KIV in a future issue. This comment is resolved for now.

File: src/main/java/seedu/taassist/logic/commands/DeletecCommand.java (hunk 1 above)
Comment (Bubbl3T) [reply src/main/java/seedu/taassist/logic/commands/DeletecCommand.java]: Good concern. However, the fix might be slightly breaking abstraction, we might need to look into the implementation in the future. Will get it fixed in the next commit.

File: src/main/java/seedu/taassist/logic/commands/DeletecCommand.java [hunk 3]
```diff
@@ -4,11 +4,15 @@
...
 
+import java.util.Collections;
+import java.util.HashSet;
+import java.util.List;
 import java.util.Set;
 
 import seedu.taassist.logic.commands.exceptions.CommandException;
 import seedu.taassist.model.Model;
 import seedu.taassist.model.moduleclass.ModuleClass;
+import seedu.taassist.model.student.Student;
```
Comment (njxue) [inline src/main/java/seedu/taassist/logic/commands/DeletecCommand.java:19]: I think the constructor should also perform a null check with `requireAllNonNull()`
 (Github doesnt allow reviewing a line that wasn't changed so this comment is here)

**Review by njxue — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/taassist/logic/commands/DeletecCommand.java (hunk 3 above)
Comment (Bubbl3T) [reply src/main/java/seedu/taassist/logic/commands/DeletecCommand.java:19]: I find that there are other command constructors having the same problem. Fixed in the next commit.

**Review by njxue — APPROVED** [review]

**Comment by Berted** [comment]
Let's wait for PR #148 to be merged prior to merging this PR. As I believe #148 causes quite a few breaking changes to this PR that will need to be resolved.

File: src/main/java/seedu/taassist/logic/commands/DeletecCommand.java [hunk 4]
```diff
@@ -45,14 +52,20 @@ public CommandResult execute(Model model) throws CommandException {
                     model.getModuleClassList()));
         }
 
-        List<Student> students = model.getFilteredStudentList();
+        List<Student> students = model.getTaAssist().getStudentList();
```
Comment (Berted) [inline src/main/java/seedu/taassist/logic/commands/DeletecCommand.java:55]: Perhaps it would be better if we can move `deleteModuleClass` logic to `Model` to improve abstraction. However, this is servicable for now.

File: src/main/java/seedu/taassist/logic/commands/DeletecCommand.java [hunk 5]
```diff
@@ -45,14 +52,20 @@ public CommandResult execute(Model model) throws CommandException {
...
         for (Student student : students) {
             if (!Collections.disjoint(student.getModuleClasses(), moduleClasses)) {
                 Set<ModuleClass> assignedClasses = new HashSet<>();
                 assignedClasses.addAll(student.getModuleClasses());
                 assignedClasses.removeAll(moduleClasses);
+
+                List<StudentModuleData> studentModuleData = student.getModuleDataList();
+                List<StudentModuleData> updatedModuleData = studentModuleData.stream()
+                        .filter(data -> !assignedClasses.contains(data.getModuleClass()))
```
Comment (Berted) [inline src/main/java/seedu/taassist/logic/commands/DeletecCommand.java:64]: Using `contains` is correct for now. However, since `ModuleClass` should use `isSame` to check for equality, this might be an issue in the future, will KIV in a future issue.

**Review by Berted — APPROVED** [review]
LGTM! There are some optional comments that you can fix if you have the time. If not, feel free to open issues regarding these remarks for it to be fixed in the future.

File: src/main/java/seedu/taassist/logic/commands/DeletecCommand.java (hunk 4 above)
Comment (Bubbl3T) [reply src/main/java/seedu/taassist/logic/commands/DeletecCommand.java:55]: Mentioned in new issue #151.

File: src/main/java/seedu/taassist/logic/commands/DeletecCommand.java (hunk 5 above)
Comment (Bubbl3T) [reply src/main/java/seedu/taassist/logic/commands/DeletecCommand.java:64]: Mentioned in new issue #152.
