### PR TITLE
Fix inconsistency between `addc` and `deletec` commands.

### LINKED ISSUE #143: Inconsistency in dealing with multiple class inputs.
I think the implementation for dealing with multiple classes is inconsistent with other commands. We might want to look into how we want the system to react when some of the classes does not exist for `deletec` commands or already exist for `addc` command.

A similar problem might exist for Session related commands.

_Originally posted by @Bubbl3T in https://github.com/AY2223S1-CS2103T-T12-1/tp/pull/141#discussion_r993477777_

### PR DESCRIPTION
**Pull request by Bubbl3T**
Resolves #143.

### CODE REVIEW

**Comment by Bubbl3T** [comment]
Resolves #235.

File: src/main/java/seedu/taassist/logic/commands/DeletecCommand.java [hunk 1]
```diff
@@ -41,13 +44,48 @@ public DeletecCommand(Set<ModuleClass> moduleClasses) {
...
+                nonExistentClasses.add(moduleClass);
+            }
+        }
+        model.removeModuleClasses(existingClasses);
+
+        String message = getCommandMessage(existingClasses, nonExistentClasses);
+        return new CommandResult(message);
+    }
+
+    public static String getCommandMessage(Set<ModuleClass> existingClasses, Set<ModuleClass> nonExistentClasses) {
```
Comment (njxue) [inline src/main/java/seedu/taassist/logic/commands/DeletecCommand.java:63]: Maybe perform a requireAllNonNull check here

**Review by njxue — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/taassist/logic/commands/DeletecCommand.java (hunk 1 above)
Comment (Bubbl3T) [reply src/main/java/seedu/taassist/logic/commands/DeletecCommand.java:63]: Alright!

**Review by njxue — APPROVED** [review]
