### PR TITLE
Fix bug in assign command

### LINKED ISSUE #156: Bug: `assign` runs into RunTimException when assigning a class to students they are already in

### PR DESCRIPTION
**Pull request by njxue**
Fixes the bug in #156

### CODE REVIEW

File: src/main/java/seedu/taassist/model/student/Student.java [hunk 1]
```diff
@@ -71,6 +71,13 @@ public List<ModuleClass> getModuleClasses() {
             .collect(Collectors.toList());
     }
 
+    /**
+     * Returns true if the Student is assigned to the provided {@code moduleClass}.
+     */
+    public boolean isInModuleClass(ModuleClass moduleClass) {
+        return moduleDataList.containsMatch(moduleData -> moduleData.getModuleClass().isSame(moduleClass));
```
Comment (Berted) [inline src/main/java/seedu/taassist/model/student/Student.java]: Optionally, we can use the `UniqueList::contains` method instead? We'll just have to construct a `ModuleDate` around it. This should make the code follow the Law of Demeter more closely.

**Review by Berted — APPROVED** [review]
LGTM! There's an optional comment which can be worked on to improve abstraction. Additionally, perhaps can consider adding test cases for this specific bug to avoid future regressions.

File: src/main/java/seedu/taassist/model/student/Student.java (hunk 1 above)
Comment (njxue) [reply src/main/java/seedu/taassist/model/student/Student.java]: Implemented your suggestion 👍
