### PR TITLE
Fix bug: clear command does not exit focus mode

### LINKED ISSUE #254: Bug: Running `clear` in focus mode does not clear the sessions

### PR DESCRIPTION
**Pull request by RezwanArefin01**
Fixes #254.

### CODE REVIEW

File: src/main/java/seedu/taassist/logic/commands/ClearCommand.java [hunk 1]
```diff
@@ -13,11 +13,13 @@ public class ClearCommand extends Command {
     public static final String COMMAND_WORD = "clear";
     public static final String MESSAGE_SUCCESS = "TA-Assist has been cleared!";
 
-
     @Override
     public CommandResult execute(Model model) {
         requireNonNull(model);
+        if (model.isInFocusMode()) {
```
Comment (Berted) [inline src/main/java/seedu/taassist/logic/commands/ClearCommand.java]: To not break the abstraction barrier as much, would it be better for this to focusMode check to be handled by `Model::setTaAssist` instead? Then `ModelManager`'s test should be tested instead of `ClearCommand`'s

**Review by Berted — CHANGES_REQUESTED** [review]
Nice catch! However, a section of the code perhaps should be moved to improve separation of concern?

In addition, these bugs related to UI not exiting focus mode could have also been prevented by applying an Observable pattern to the focusedClass. Maybe we can consider doing so in the future.

**Review by Berted — APPROVED** [review]
LGTM!
