### PR TITLE
Fix bug with class command

### LINKED ISSUE #92: Class command running into error with the command `class c/CS1101S`.
The `class` command to enter focus mode will encounter a runtime error when we enter a class with the class prefix. This is undesirable and should be fixed.

### PR DESCRIPTION
**Pull request by njxue**
Fixed the class command by using the `parseModuleClass` in `ParserUtil` to return the `ModuleClass` instead of calling the `ModuleClass` constructor

### CODE REVIEW

File: src/main/java/seedu/taassist/logic/parser/ClassCommandParser.java [hunk 1]
```diff
@@ -3,6 +3,7 @@
 import static seedu.taassist.commons.core.Messages.MESSAGE_INVALID_COMMAND_FORMAT;
 
 import seedu.taassist.logic.commands.ClassCommand;
+import static seedu.taassist.logic.parser.ParserUtil.parseModuleClass;
```
Comment (Bubbl3T) [inline src/main/java/seedu/taassist/logic/parser/ClassCommandParser.java]: I think the static import should be grouped with line 3 to be consistent with the style guide. You might want to check your project settings regarding the imports too.

**Review by Bubbl3T — APPROVED** [review]
LGTM!

File: src/main/java/seedu/taassist/logic/parser/ClassCommandParser.java (hunk 1 above)
Comment (njxue) [reply src/main/java/seedu/taassist/logic/parser/ClassCommandParser.java]: yea haha my gradle build failed. Fixed
