### PR TITLE
Fix `deletes` command

### LINKED ISSUE #214: Bug: uncaught RuntimeException in `deletes` even when a session exists
image

### PR DESCRIPTION
**Pull request by njxue**
Resolves #214

### CODE REVIEW

File: src/main/java/seedu/taassist/model/uniquelist/UniqueList.java [hunk 1]
```diff
@@ -53,18 +53,35 @@ public void add(T toAdd) {
...
+    private int indexOf(T target) {
+        requireNonNull(target);
+        for (int i = 0; i < internalList.size(); i++) {
+            if (internalList.get(i).isSame(target)) {
+                return i;
+            }
+        }
+        return -1;
+    }
+
```
Comment (Bubbl3T) [inline src/main/java/seedu/taassist/model/uniquelist/UniqueList.java]: Since the `-1` value is no longer used, perhaps we can make the following changes.
```suggestion
    /**
     * Returns the index of an element in the list that has the same identity {@code target}.
     *
     * @param target target element to find.
     * @return index of the found element in the list. 
     * @throws ElementNotFoundException If no such element can be found.
     */
    private int indexOf(T target) {
        requireNonNull(target);
        for (int i = 0; i < internalList.size(); i++) {
            if (internalList.get(i).isSame(target)) {
                return i;
            }
        }
        throw new ElementNotFoundException();
    }

```

File: src/main/java/seedu/taassist/model/uniquelist/UniqueList.java [hunk 2]
```diff
@@ -53,18 +53,35 @@ public void add(T toAdd) {
     public void setElement(T target, T editedElement) {
         requireAllNonNull(target, editedElement);
 
-        int index = internalList.indexOf(target);
-        if (index == -1) {
+        if (!contains(target)) {
```
Comment (Bubbl3T) [inline src/main/java/seedu/taassist/model/uniquelist/UniqueList.java]: We can let `indexOf` throw the `ElementNotFoundException` instead.

**Review by Bubbl3T — CHANGES_REQUESTED** [review]
Since we are no longer using the `-1` index to indicate that the element cannot be found, we can perhaps let `indexOf` throw the `ElementNotFound` exception instead.

File: src/main/java/seedu/taassist/model/TaAssist.java [hunk 3]
```diff
@@ -162,20 +163,36 @@ public void removeModuleClass(ModuleClass moduleClass) {
...
                 .collect(Collectors.toList());
         setStudents(updatedStudents);
-        setModuleClass(moduleClass, moduleClass.removeSession(session));
     }
 
-    //// util methods
+    private ModuleClass removeSessionFromModuleClass(ModuleClass moduleClass, Session session) {
+        requireAllNonNull(moduleClass, session);
+        ModuleClass newModuleClass = moduleClass.removeSession(session);
+        setModuleClass(moduleClass, newModuleClass);
```
Comment (RezwanArefin01) [inline src/main/java/seedu/taassist/model/TaAssist.java]: Would it work if ` setModuleClass(moduleClass, newModuleClass);` is done once in the end? Then this function won't be needed in `removeSessions`.

File: src/main/java/seedu/taassist/model/uniquelist/UniqueList.java [hunk 4]
```diff
@@ -53,18 +53,35 @@ public void add(T toAdd) {
...
+        for (int i = 0; i < internalList.size(); i++) {
+            if (internalList.get(i).isSame(target)) {
+                return i;
+            }
+        }
+        return -1;
+    }
+
     /**
      * Removes the equivalent element from the list.
```
Comment (RezwanArefin01) [inline src/main/java/seedu/taassist/model/uniquelist/UniqueList.java:84]: While we are at it, update this method to remove the same identity element too. 
This should fix #221.

File: src/main/java/seedu/taassist/model/TaAssist.java (hunk 3 above)
Comment (njxue) [reply src/main/java/seedu/taassist/model/TaAssist.java]: yea it works!

**Review by Bubbl3T — APPROVED** [review]
LGTM!
