### PR TITLE
Fix data loading bugs and improve storage tests

### LINKED ISSUE #110: Write testcases related to a class not existing
Need testcases for the following places where a class does not exist in the app:
- Add command
- Edit command
- Storage load

### LINKED ISSUE #187: Integrate `SessionData` in the testing framework
Currently we cannot include any `SessionData` in `typicalStudentsTaAssist.json`. This is due to some classes containing `Identity<T>`  objects that are checked for equality through `equals` method. 

Example of issues among others: 
- `TaAssist` contains a `UniqueList` of `ModuleClass`. The `ModuleClass` should be compared with `isSame` but `TaAssist` is compared with `equals`. 
- `UniqueList<T>` itself contains `Identity<T>` elements while being compared with `equals`!! This currently checks for exact equality of elements, even the order. This is making writing some tests very hard. 

A quick fix would be to make some of the `equals` method compare with `isSame` instead. However, that breaks the philosophy of the `Identity<T>` abstraction, since originally `equals` was supposed to check for equality in every field. There is also the chance that by doing so we will lose some test-ability (i.e. not detecting changes in some fields). 

Another possible fix is to make those classes `Identity<T>` too. Then we will need to change the tests that check for equality to use identity instead. Thoughts?

Related: #147.

### LINKED ISSUE #188: Add tests for `SessionData` and `StudentModuleData` and their JSON-adapted versions

### LINKED ISSUE #334: Set constraints for grade
Currently grade accepts any value. It can look something like this:

Screenshot_20221103_125454

### LINKED ISSUE #347: Uncaught `NullPointerExecption` when JSON file has missing fields
For some newly added `JsonAdapted*`, the case that a field is missing in the json file is not handled.  
In these cases, the app crashes without printing any error message in logger or showing the alert window.

### LINKED ISSUE #348: Missing `grade` field is initialized to 0 when loading
Expected behavior: throws a data loading error. 

This is likely a Jackson behavior. A remedy is to save the grade as string and parse it when loading. Jackson seems to have a way to enable writing numbers as string too, as in this answer https://stackoverflow.com/a/26026579.

### PR DESCRIPTION
**Pull request by RezwanArefin01**
This PR: 
- Resolves #110 (except add command test, can be closed for now). 
- Resolves #187. Implementation: 
  - When a new `StudentModuleData` is constructed, remove the sessions from the passed in `ModuleClass`. 
  - When a new `SessionData` is constructed, remove the `Date` field from the passed in `Session` (reset to current date). 
      - So when `view` prints the session, it will print in alphabetical order of the session names, which is intended. 
      - This can trigger an *ultra rare* bug that if TA-Assist is opened some nano seconds before midnight, the `view` command might show the sessions in some unintended order.
- Resolves #188. 
- Resolves #347. It was an oversight.
- Fixes #348. 
- Resolves #334. 
- Updates the initial data with some sessions and grades.
- Covers everything in `storage` except two getter methods.

### CODE REVIEW

File: src/main/java/seedu/taassist/storage/JsonAdaptedSessionData.java [hunk 1]
```diff
@@ -5,24 +5,28 @@
...
+import seedu.taassist.model.student.SessionData;
 
 /**
  * Json-friendly version of {@link SessionData}.
  */
 class JsonAdaptedSessionData {
 
+    public static final String MISSING_NAME_MESSAGE = "Session's name field is missing!";
+    public static final String MISSING_GRADE_MESSAGE = "Session's grade field is missing!";
+    public static final String INVALID_GRADE_MESSAGE = "Session's grade field is invalid!";
```
Comment (Bubbl3T) [inline src/main/java/seedu/taassist/storage/JsonAdaptedSessionData.java]: Might want to name the variable as `MESSAGE_MISSING_NAME` for consistency with other classes. Same for the other variables.

File: src/main/java/seedu/taassist/model/student/StudentModuleData.java [hunk 2]
```diff
@@ -28,15 +28,20 @@ public class StudentModuleData implements Identity<StudentModuleData>, Comparabl
      */
     public StudentModuleData(ModuleClass moduleClass) {
         requireNonNull(moduleClass);
-        this.moduleClass = moduleClass;
+        /*
+         * The following line is to remove references to session from the module class.
+         * In a StudentModuleData, only the name of the module class is used. Also in the
+         * JSON file, only the name is saved.
+         */
+        this.moduleClass = new ModuleClass(moduleClass.getClassName());
```
Comment (Bubbl3T) [inline src/main/java/seedu/taassist/model/student/StudentModuleData.java:36]: Might become an issue if the stored `moduleClass` is used to check for existing sessions in the module class. Should be ok for now though since that is not what we are doing.

**Review by Bubbl3T — APPROVED** [review]
LGTM!

File: src/main/java/seedu/taassist/model/student/StudentModuleData.java (hunk 2 above)
Comment (RezwanArefin01) [reply src/main/java/seedu/taassist/model/student/StudentModuleData.java:36]: > Might become an issue if the stored moduleClass is used to check for existing sessions in the module class.

This is not the intended use case for this moduleClass. The real moduleClass object is in model and should be retrieved for the actual session list. This moduleClass is sort of a reuse of the class, otherwise it would be a string only.

File: src/main/java/seedu/taassist/storage/JsonAdaptedStudent.java [hunk 3]
```diff
@@ -8,19 +8,19 @@
...
 import seedu.taassist.model.student.Student;
+import seedu.taassist.model.student.StudentModuleData;
 
 /**
  * Json-friendly version of {@link Student}.
  */
 class JsonAdaptedStudent {
 
-    public static final String MISSING_FIELD_MESSAGE_FORMAT = "Student's %s field is missing!";
+    public static final String MESSAGE_MISSING_FIELD_FORMAT = "Some student's %s field is missing!";
```
Comment (Berted) [inline src/main/java/seedu/taassist/storage/JsonAdaptedStudent.java]: Perhaps just make this `Student's %s field is missing`? to make it consistent with other Storage class's responses.

**Review by Berted — APPROVED** [review]
LGTM! Just an optional comment regarding consistency.
